### ISSUE TITLE
Fee on withdrawals

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#101]
- user pays a fee (a percentage of his share) when withdrawing their stake
- fee is set per vault 
- fee is set as a percentage of the user's share (`function setFee(uint256 _pid, uint256 _newValue)`) and is payable in the vault token
- `setFee` is callable only by one address (`address feeSetter`) that is configurable by governance (in the timelock, I guess)
- feeSetter at first will be governance, but can be later set to another address

So we have:
- contract var `address feeSetter`
- function `setFeeSetter(address _newFeeSetter) onlyGovernance`
- modifier `onlyFeeSetter` which requires that the caller is either the `feeSetter`, or, if `feeSetter == address(0)`, the owner
- new function `function setFee(uint256 _pid, uint256 _newValue) onlyFeeSetter`,
  - fee is required to be < 2% (please doublecheck this)
- A change in `_withdraw`: fees are being sent to governance on withdrawal

**Comment by ben-kaufman** [comment]
Also, should fee apply for _emergencyWithdraw?
