### ISSUE TITLE
Make the allocation point settable (voting escrow api)

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#102]
Context for this change is because we will want to implement a curve-style gauge in which "veHATs" token holders decide how to allocate the rewards

## A Plan

- create a new separate contract to manage to distribution of rewards to separate pools: `RewardController`
- the pools contract (or in a later stage, each separate pool contract) reads from `RewardController` how much rewards it gets to distribute

### changes in `HATVaults`
- new state var `HATVaults.rewardController` 
   - is an address
   - settable by governance
- remove `HATVaults.calcPoolReward` and replace it with a call to `HATVaults.rewardController.poolReward(_pid)`
- remove `_allocPoint` argument from `addPool` and from `setPool`
### new contract `RewardController` 
- is ownable
- has a `allocPoints` mapping that maps poolIds to allocpoints
- `setAllocPoint(pid, allocpoint) onlyOwner` to set the allocpoint
- the following functions  (to remove from HATVaults and use in RewardController): 
    -  `globalPoolUpdates` 
   - `calcPoolReward` 
   - `pendingReward` (this is just a getter function, we could also consider removing it)

**Comment by ben-kaufman** [comment]
So where should the value of _allocPoint come from now when calling addPool or setPool?
