### ISSUE TITLE
add a `sweeptoken` function to the vesting contract

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#108]
to recover tokens that are sent to the contract by mistake

* Function signature: `sweepToken(address _token)`
* Sends all `_token`s held by `address(this)` to the token owner (or to the beneficiiary if there is no owner)
* Can only be called by the owner (or by the beneficiary if there is no owner)
* Requires that the `_token` address is not equal to the tokens being vested in the vesting contract

**Comment by jellegerbrandy** [comment]
- tokens go the owner, or to beneficiary if owner is 0
- calleable only by the owner

**Comment by ben-kaufman** [comment]
Where should that be? `TokenLock.sol`?
