### ISSUE TITLE
Add "description hash" arguments  to submitClaim()

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#109]
Shay writes "Also add two description hashes (ipfs cid) that points to the encrypted message and decrypted message (with session key)"

**Comment by ben-kaufman** [comment]
Yeah not sure I understand this one...

**Comment by jellegerbrandy** [comment]
I guess what we want to do here is add the possibilty to send some string together with the claim that you submit, that proves that you actually are submitting a particular claim. 

I'll ask shay, but for now I take this as meaning that we do this:

```
function submitClaim(uint256 _pid, address _beneficiary, uint256 _severity, string _descriptionHash) {
   [do not change anything here except the event]
  emit SubmitClaim(_pid, msg.sender, _beneficiary, _severity, _descriptionHash);
}

**Comment by shayzluf** [comment]
@jellegerbrandy i hope this is unblocking you
