### ISSUE TITLE
Deploy a separate contract instance for each vault

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#124]
This issue is closely related to #270 

## How to implement this
The main deviation with our current approach is that we would need a separate contract for each Vault, and we would have a HatVaults contract that would serve as a contract registry and is responsible for distributing the rewards over the vaults.

-  *Vault Registry*:
    - is factory for hatVault
    - is registry for hatVault instances, which will be deployed as upgradeable proxy
 
 - *Vaults* will hold most (but not all) of the logic of the current HatVaults contract:
    - deposit 
    - claims
    - committees
 

## VaultRegistry

* Terminology: instead of "pools" we talk about "vaults" (to accomodate erc4626)
* Remove logic for generting and keeping track of pool ids - instead a new vault is a new (proxy) contract deployment, and vaults are identified by their addresses
* `VaultRegistry.vaults` is a mapping from vault addresses to ....(tbd)
* new function `createVault` replaces the current `addPool` function
  - same params as addPool
  - instead of adding a record to poolInfos, we create a new vault proxy instance with the given params
* VaultRegistry is `Ownable`, and the owner controls the settings
* The registry also manages a number of system-wide settings (meaning this info is stored in the registry, and there are corresponding setters (that are now in teh Params contract))
   - `feeSetter`
   - `arbitrator` (although we can also decide to have an arbitrator-per-vault)
   - all data in `generalParamaters`
   - `challengePeriod`, `challengeTimeOutPeriod`
   - `swapToken`
   - `whitelistedRouters`

* Open question: can anyone call `createVault`? Why not?

## Vault

* inherits from the same contracts as current `HATVaults` classes. These classes will need some changes which are listed below
* Proxy implementation contract
* `initialize` function takes the following params that will be saved as state variables on the vault instance:
    - `token` (currently called `lpToken`)
    - `rewardController`
    - `bountyInfo`
    - `committee`
    - `descriptionHash` (will not save this but emit an event, just as now)
    - `registry`: the vault registry (this is new)
    
* In the inherited classes, all functions that take a `pid` argument are changed, as they now have direct access to the data, and all mappings that map poolIds to data become direct pointers to data. For example:
   - `poolInfos: pid --> poolInfo` becomes `poolInfo: poolInfo` (or perhaps even better: the poolInfo keys become state variables)
   - `submitClaim(_pid, _beneficiary, ...)` becomes `submitClaim(_beneficiary, ....)`
   - `activeClaims: poolIds -> claimIds` becomes `activeClaim: claimId`
* The funds for the bounty are held by the vault contract. This makes it impossible to mix funds from different vaults. This means we can remove teh `poolInfo.balance` property (and the correlated bookkeeping) and instead read the balance directly from the token
* 
   -

**Comment by ben-kaufman** [comment]
So removing balance is problematic I think when HATToken is also the LPToken.
