### ISSUE TITLE
make sure all code follows solidity style guide

### ISSUE THREAD

**Issue by lirona** [hats-finance/hats-contracts#143]
https://docs.soliditylang.org/en/v0.5.3/style-guide.html

**Comment by lirona** [comment]
also have all function args, events etc be uniform

**Comment by jellegerbrandy** [comment]
I think we could make a checklist in this issue of concrete things to address regarding coding style:

- [ ] event arguments should all start with underscore
- [ ] function arguments should all start with underscrore
- [ ] use `poolId` insted of `pid` everywhere

**Comment by jellegerbrandy** [comment]
I guess we have greatlooking code now
