### ISSUE TITLE
change semantics for getRewardPerBlock

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#148]
`getRewardPerBlock` takes as its argument "the pool id plus 1" (it uses the zero value to return "the reward over all pools"). 

This is confusing. 

Proposal: to change the semantics, so that `getREwardPerBlock(poolId)` just means what is expected, and `getRewardPerBlock(max(uint256))` returns the reward over all pools

**Comment by lirona** [comment]
signed integer for -1 flag?

**Comment by lirona** [comment]
maybe just split to 2 functions?

**Comment by ben-kaufman** [comment]
I guess this can be closed as irrelevant
