### ISSUE TITLE
HATVaults contract too big 

### ISSUE THREAD

**Issue by lirona** [hats-finance/hats-contracts#149]
Strategies for making the contracts smaller:

- refactor all `Set...` events (i.e. SetFeeSetter, SetCommittee, SetChallengePeriod, etc, there are like 16, and replace with events like`SetGlobalParam(_paramName, uint _oldValue, uint _newValue)` `SetGlobalParam(_paramName, address _oldValue, address _newValue)` and `SetPoolParam(_poolId, _paramName, _oldValue, _newValue)`

- similarly, create a generic `setParam(_name, _value)` and `setPoolParam(_name, _value)`

- Move certain functions to a library, as is done in https://github.com/hats-finance/hats-contracts/pull/165

**Comment by jellegerbrandy** [comment]
This is postponed for now
