### ISSUE TITLE
in _deposit, do not assume that the call to transfer does transfer exactly the right amount of tokens

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#159]
instead, check the difference in balance

**Comment by jellegerbrandy** [comment]
same with all other places where pool.balance is updated, like withdraw

**Comment by ben-kaufman** [comment]
What's the reason for that?

**Comment by jellegerbrandy** [comment]
the reason is that we might have lpTokens that tax transactinons - i.e. tokens that when calling `transfer(amount)` do no necessarily transfer exactly `amount` of tokens
