### ISSUE TITLE
remove REWARD_PER_BLOCK variable

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#183]
Like this:
- remove `REWARD_PER_BLOCK` variable
- rename `rewardMultipliers` to `rewardPerEpoch` (it represents how much rewardTokens are paid out in each of the 24 epochs)
- rename `MULTIPLIER_PERIOD` to `EPOCH_LENGHT`
- remove `getMultipliers(fromblock, toblock)` and move that logic to `getRewardsForBlockRange`

**Comment by ben-kaufman** [comment]
Should there be anything instead of the REWARD_PER_BLOCK or just remove it from the calculation it's used in?
