### ISSUE TITLE
reorder state variable declaration

### ISSUE THREAD

**Issue by lirona** [hats-finance/hats-contracts#186]
have them in an order we'll be happy to keep forever :)
https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies#storage-collisions-between-implementation-versions

**Comment by jellegerbrandy** [comment]
It would perhaps also be a good idea to move some definitions out of `Base.sol` and closer to where they are actually used. (The idea is taht `Base.sol` only has declaratinos that are common to all classes)

**Comment by lirona** [comment]
https://docs.soliditylang.org/en/latest/style-guide.html#order-of-layout

**Comment by lirona** [comment]
https://docs.soliditylang.org/en/latest/style-guide.html#order-of-functions
