### ISSUE TITLE
use a claimId instead of poolId to refer to claims

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#200]
changes in the api:

1. Each claim gets a unique id, which is `keccak(poolId, block.number)`
1. `submittedClaims` becomes a mapping from `claimId`s to `SubmittedClaim` objects
1. a new mapping `activeClaims: poolId -> claimId`: when a claim is submitted, this is set, and when a claim is accepted or dismissed, it is reset to 0. 
1. The activeClaims mapping is used in `modifier noSubmittedClaims` where we check if `activeClaims[poolId] != 0`
1. `submitClaim` should  generate a claimId and return it. The claimID is  `keccak(poolId, block.number)`. In theory it is possible to submit two claims in the same block (in practice this should never happen), so we should check uniquenesss by checking that `activeClaims[newClaimId]` is not set yet
1.  `approveClaim` and `dismissClaim` now take `_claimId` as a parameter instead of `_poolId`

**Comment by lirona** [comment]
1. you think it will be possible to get 2 claims submitted in the same block? hard to imagine but we can also use the `_descriptionHash` instead of the `block.number`
3. `claim` is currently used to describe a hacker's submission of a vulnerability, should rename that anyway
6. need to also take the `pid` right?

**Comment by lirona** [comment]
`swapAndBurns` also need to change to be a mapping from `claimId` and not `pid`

**Comment by lirona** [comment]
> > 1. you think it will be possible to get 2 claims submitted in the same block? hard to imagine but we can also use the `_descriptionHash` instead of the `block.number`
> > 2. `claim` is currently used to describe a hacker's submission of a vulnerability, should rename that anyway
> > 3. need to also take the `pid` right?
> 
> 1- +1 keccak(poolId,descriptionHash) is it possible @jellegerbrandy 3- +1 `submitClaim` is misleading (I would assume its the function the hacker call when he submits a vulnerability )

i think it should be called something like `submitVulnerability` and `submitBountyPayout`

**Comment by jellegerbrandy** [comment]
1. The description hash is user-controlled and so is of no use to generate unique ids guys, think about it
3. Ok, I remember now we had this dicussion before, ignore my point 3. I am sorry to have brought it up, but I am not again into a discussion on how to name functions, we did a refactor of that a few weeks ago and we had ample time to discuss there. 
6. Why would we need to add the poolID to the function sig? If we have the claimID, we know the poolID

**Comment by lirona** [comment]
so this is the code that creates the description hash:
https://github.com/hats-finance/hats/blob/d769a83a20086f4963ae66309222de0cc89ea730/src/components/Vulnerability/Submit/components/SubmitReview/SubmitReview.tsx#L40
it pgp encrypts the info of the submission and then does a sha256 on the encrypted data. looks to me like this could actually just be used as the claim Id itself no?
