### ISSUE TITLE
Test pass even if coverage is diminished

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#214]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/1306173/172053906-1612a519-24a8-4e06-8e16-34be6c1a7fab.png">

**Comment by ben-kaufman** [comment]
Hmm I think this might be a glitch in coveralls, see this also:
<img width="847" alt="Screen Shot 2022-06-18 at 19 25 40" src="https://user-images.githubusercontent.com/10667901/174460012-941d6cbf-e109-4a12-b3dc-e5d6035e856c.png">
 
Says coverage is lower than 100% but still up
