### ISSUE TITLE
consider removing MINIMAL_DEPOSIT (audit #1)

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#226]
> 
> 
> Adam Kolar | g0, [09/06/2022 14:46]
> I wonder if instead of having a constant MINIMUM_DEPOSIT it wouldn't be better to have a dynamic minimum deposit value equal to: pool.balance / pool.totalShares
> 
> Adam Kolar | g0, [09/06/2022 14:47]
> If I understand correctly, the purpose of MINIMUM_DEPOSIT is to prevent people from depositing while receiving 0 shares.
> 
> Adam Kolar | g0, [09/06/2022 14:50]
> Note that analogous problem can occur in withdraw after pool balance is reduced by a claim, one share can be worth less than 1 lpToken and that can lead to withdrawal amount being rounded to 0.
> 
> Adam Kolar | g0, [09/06/2022 14:54]
> Also since there's an implication that transferredAmount can differ from _amount (due to transfer fee tokens?) you should probably check minimum deposit against transferredAmount or even better just check that userShares > 0.
> 
> jelle gerbrandy, [09/06/2022 15:41]
> [In reply to Adam Kolar | g0]
> the MINIMUM_DEPOSIT logic is there since v1 and I agree it is a bit clumsy - just checking that userShares > 0 is much more elegant, we should try that out. Personally, I am not so convinced at all that we need special logic to deal with dust.
>

**Comment by jellegerbrandy** [comment]
Adam Kolar | g0, [09/06/2022 15:49]
[In reply to jelle gerbrandy]
You could actually replace the dust logic with more general _minShares check in the deposit function and maybe _minTokens in the withdraw function.

**Comment by ben-kaufman** [comment]
What do you mean exactly with  _minShares logic?

**Comment by ben-kaufman** [comment]
Also, without the minimum deposit we won't be able to have the rewardDepositors no?

**Comment by jellegerbrandy** [comment]
honestly I am not understanding at all what MINIMUM_DEPOSIT is doing in rewardDepositors

**Comment by ben-kaufman** [comment]
So about rewardDepositors, this was really weird for me too but I think I understand now. So the minimum deposit was there to ensure that the pool balance will not go too high so that if someone deposits more than the minimum reward they might still get 0. But now it will no longer be an issue

**Comment by ben-kaufman** [comment]
But now it basically means if you deposit in a pool with big balance you might overpay for a share, what should we do about that (if at all)?

**Comment by jellegerbrandy** [comment]
ok, a scenario:
1- first user deposits 1 WEI and gets 1 share
2- someone calls rewardDepositors and deposits `R` tokens (lets say it's worth 1M$)
3- second user deposits `d` tokens and gets  `pool.totalShares * transferredAmount / lpSupply = 1 * d/(R+1)` tokens and so
  a) must depoist at least R (i.e. > 1M$) tokens to get a share
  b) if deposits 1.9M$ tokens, will get `1.9/R = 1 share`, which will give her a claim on 50% of 2,9R tokens, i.e. she will overpay by almost .5M$

There is an attack here - anyone can do steps 1 and 2 and then take some of the share of the others. 

So this is not acceptable, of course

So basically, the logic is:

`sharesRecevied = totalShares * yourDeposit / (totalDeposits + rewards)`

Note that if no rewards are added and no payouts are done, then totalShares == totalDeposits, and so all is well.
If only payouts re done, than totalDeposits < totalShares, and there will be rounding errors, but they will not be a problem.

The problem is with the rewards here - basically, if `(totalDeposits + rewards) >> totalShares`, there is a problem. 
 
The original lines in rewardDepositors are, which checks exactly that 🔥 

```  if ((poolInfos[_pid].balance + _amount) / MINIMUM_DEPOSIT >=
            poolInfos[_pid].totalShares) revert AmountToRewardTooBig();```
```
So I guess we should not remove that 😅

**Comment by ben-kaufman** [comment]
Yeah that's just the overpayment I mentioned above. But I left it intentionally because it's just possible for the depositors to calculate the correct amount to deposit, which seemed to me to make more sense than limiting the reward functionality...
But I guess we can also do the opposite and ensure no overpayment is done by limiting the reward depositors functionality

**Comment by ben-kaufman** [comment]
Or we could calculate the amount overpaid and return/ not take it... What do you think?

**Comment by jellegerbrandy** [comment]
I'd be for adding the check in rewardDepositors, i.e. check in rewardDepositors that there are enough totalShares. I guess that would be enough.

(I asked shay on tg if we can just remove rewardDepositors, which makes everything more straightforward, so let's wait for his answer)

**Comment by jellegerbrandy** [comment]
OK, we will remove the `rewardDepositors` function which will allow us to remove all this minimumdeposit stuff
