### ISSUE TITLE
setAllocPoint does not update lastProcessedAllocpoint in the pool (audit #2)

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#228]
- 2) I've been thinking about how RewardController.poolsAllocPoint change is handled, when RewardController.setAllocPoint is called a new checkpoint is created for totalAllocPoint in globalPoolUpdates, but there's no checkpointing system for poolsAllocPoint values. I think this can lead to new poolsAllocPoint value being used with old totalAllocPoint value. I think this can even lead to _allocPoint being larger than _totalAllocPoint in getRewardForBlocksRangeAdam Kolar | g0, [09/06/2022 15:14]
This concerns specifically the case when pool alloc point is changed without the pool being updated. So that poolInfos[_pid].lastProcessedTotalAllocPoint will end up pointing to globalPoolUpdates value that reflected a different alloc point than the newly set.
    
    Adam Kolar | g0, [09/06/2022 15:15]
    A simple solution seems to be to ensure a pool is always updated before its alloc point value is changed.

**Comment by ben-kaufman** [comment]
Ok so to solve this, I see 2 possible options:

1. Move the lastProcessedTotalAllocPoint to the rewardController and have the hatvaults address saved as a "role" so it can call it (as it was in its first version).
2. Have the hatvaults saved in the reward controller and just call update pool when setAllocPoint  is called.

Both require saving the hatvaults address in the rewardcontroller again which creates mutual dependency and is ugly, but I don't see another way, or any other ideas?

**Comment by ben-kaufman** [comment]
No because you need the totalShares to calculate the rewardPerShare so again can't do without mutual dependency (like limiting the caller address to the hats vaults)

**Comment by ben-kaufman** [comment]
Tbh I guess we could just deploy the reward controller (or well a proxy because the actual one would be too heavy) from the initialize and make it save the deployer address so we have this access control... But not sure we want that?
