### ISSUE TITLE
fix linter warnings on github actions

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#247]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1306173/174758966-91939f8d-6216-4a79-9182-a2a6d199902e.png">

I suspect the problem here is that solhint does not understand the errors yet. There are different errors here (just run `npx hardhat check`)

**Comment by ben-kaufman** [comment]
Looks like hardhat solhint uses some old version which doesn't support custom errors.

**Comment by ben-kaufman** [comment]
But also with the regular solhint latest version there are a few warnings
<img width="1062" alt="Screen Shot 2022-06-21 at 09 50 24" src="https://user-images.githubusercontent.com/10667901/174815934-065d2dfa-4638-4a15-aa65-1e53fa0bdecc.png">
