### ISSUE TITLE
HATToken.sol not Gas Optimized

### ISSUE THREAD

**Issue by DevABDee** [hats-finance/hats-contracts#274]
Not a bug but it can be a big problem. As the contract HATToken.sol includes so many `require` statements with error messages, it will be too much gas costly. As it stores full-length strings

A simple solution would be to use `Custom Errors` with if-else revert statements, instead

[For More Information, Check This.](https://ethereum.stackexchange.com/questions/101782/requirecondition-message-vs-revert-with-a-custom-error-which-is-better-a)

**Comment by DevABDee** [comment]
Just made a Pull request #275 with the solution and more gas-optimized contract :)
Thanks

**Comment by jellegerbrandy** [comment]
Thank you very much, again, for this pr. We are not actively developing the token contract anymore as it is already deployed.
