### ISSUE TITLE
Individual vaults ownership

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#277]
Currently, with the new ERC4626, each vault has its own owner, which starts as the owner of the registry at the time the vault is created. This means that if the owner of the registry changes, the owner of the existing vaults does not change unless manually done for each. This has the negative side of either the owner having to call change ownership on each vault, or the vaults having different owners. Yet this can also be seen as a feature, in case we would like to allow vaults to have their own owners.

We should decide then if we want to keep ownership managed on the individual vault level, or always ready the ownership from the registry.

**Comment by ben-kaufman** [comment]
Thinking about it more probably the owner should always be the registry.owner() 

Although some stuff should probably move to management of the committee like the vesting (of regular tokens) and pause deposits.

**Comment by jellegerbrandy** [comment]
Good point, I think I agree with having just a single owner of all. This also is less of a break with v1. @shayzluf ?

**Comment by ben-kaufman** [comment]
Ok I think that makes sense, changed it in #281

**Comment by lirona** [comment]
agree, if owner is always hats governance then should always read from registry
