### ISSUE TITLE
Funds might get stuck if on swap the routing contract does not use the full amount

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#278]
If for any reason the routing contract does not use the full amount of the asset to swap for hats, the rest will stay in the contract, but not be accounted for in the balance still available to swap, this will make it stuck in the contract. Should we handle this case (considering that normally the swap contract is expected to use the full amount available) ?

**Comment by lirona** [comment]
it will not fail in case it can't swap everything?

**Comment by lirona** [comment]
it is not supposed to fail in case it can't swap everything?

**Comment by ben-kaufman** [comment]
That would depend on the routing contract not on us. So maybe, but maybe not...

**Comment by lirona** [comment]
then sounds to me that we should check

**Comment by jellegerbrandy** [comment]
So you'd update the vars with amounts that were actually swapped instead of setting them to 0?

**Comment by ben-kaufman** [comment]
Well yes that's the solution. The question is if the added complexity is actually worth it.
