### ISSUE TITLE
Emergency withdraw is no longer "emergency"

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#279]
With the current state of the emergency withdraw function, its only difference from the normal withdraw function is that it does not call the safeTransferReward of the reward controller. This is not really an "emergency" withdraw, it just withdraw without claiming the reward. This could be useful in case the reward token is paused, or if there is not enough of the reward token in the reward controller to pay the reward.

However, in both these cases, the user will likely not want to lose their reward, but would be happier with being able to just claim it at a later time. Also, in both these situations, the user will currently be forced to withdraw everything just to be able to withdraw from the vault, but they may want to just withdraw part of their deposit in the vault.

I would propose to remove the emergency withdraw function, and just completely separate the sending of rewards from updating the vault balance, so that on each action the "unclaimed" rewards of the user are registered and accumulated, and then at any time, the user can call claim reward to claim these rewards.

**Comment by jellegerbrandy** [comment]
I sort of think this is a good idea. Also others (balancer say) do that. We can also add a convenience function "withdrawAndClaim" like curve has.

@shayzluf wdyt

**Comment by shayzluf** [comment]
> I sort of think this is a good idea. Also others (balancer say) do that. We can also add a convenience function "withdrawAndClaim" like curve has.
> 
> @shayzluf wdyt

Let's do it and add withdrawAndClaim for backwards compatibility with the ui

**Comment by ben-kaufman** [comment]
OK added as part of #281
