### ISSUE TITLE
Range limit of challenge periods values

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#283]
The challenge and challenge timeout periods currently have no limits on their values. This means that a claim might cause the vault to be stuck forever if these times are set too long. We should have a limit on the value of these times like with other such important values. Also we should probably ensure challengePeriod is always shorter than the challengeTimeout period by a certain minimum, since if not, the arbitrator might challenge a claim, and it will become dismissible by anyone too soon.

**Comment by shayzluf** [comment]
Let's limit it to 90 days

**Comment by ben-kaufman** [comment]
Which? there is the challenge period, and there is the challenge timeout period, and maybe we should also have a minimum between them on how bigger the challenge timeout should be than the challenge.

**Comment by shayzluf** [comment]
> Which? there is the challenge period, and there is the challenge timeout period, and maybe we should also have a minimum between them on how bigger the challenge timeout should be than the challenge.

Wdyt about challenge period of minimum 1 day and max 5 days
Challenge timeout minimum 7 days max 90 days

**Comment by ben-kaufman** [comment]
Ok sounds fine I think

**Comment by ben-kaufman** [comment]
Should their setter be one function or leave it as 2 separate setters?

**Comment by jellegerbrandy** [comment]
About this discussion: I am not 100% sure this is a problem at all. Governance has power to block the payouts - this is explciitely so in v1 and remains in v2. In v2 I think that is most explicit in the fact that gov controls the arbitrator. 

This issue is about gov messing up the arbitration process, why would gov ever do that?

**Comment by ben-kaufman** [comment]
Well you definitely need time limits on the challenge periods otherwise it is posible for the governance to keep a claim forever so users funds are stuck and they can't withdraw...

**Comment by lirona** [comment]
agree about the limits, but don't see why challengePeriod should be shorter than the challengeTimeoutPeriod, i think they should both have minimums but not necessarily dependent on each other.

**Comment by jellegerbrandy** [comment]
Ok then let's go with shay's limits.

**Comment by lirona** [comment]
5 days to challenge a claim sounds a bit short to me

**Comment by ben-kaufman** [comment]
> agree about the limits, but don't see why challengePeriod should be shorter than the challengeTimeoutPeriod, i think they should both have minimums but not necessarily dependent on each other.

If the challengePeriod is longer than the challengeTimeoutPeriod, then the claim may be dismissible by anyone as soon as it is challenged, which gives no time for the arbitrator to resolve it.

**Comment by lirona** [comment]
> > agree about the limits, but don't see why challengePeriod should be shorter than the challengeTimeoutPeriod, i think they should both have minimums but not necessarily dependent on each other.
> 
> If the challengePeriod is longer than the challengeTimeoutPeriod, then the claim may be dismissible by anyone as soon as it is challenged, which gives no time for the arbitrator to resolve it.

oh right, i mistakenly thought the challengeTimeoutPeriod starts when the claim is challenged and not submitted.
i think actually that makes more sense and we should keep `activeClaim.ChallengedTime` instead of `activeClaim.isChallenged`
but not a big deal :)

**Comment by ben-kaufman** [comment]
Yeah that would make sense really, do you think we should do that? @jellegerbrandy @shayzluf

**Comment by jellegerbrandy** [comment]
Yes we should do that !

**Comment by ben-kaufman** [comment]
Ok, so the challenge timeout period should now have time limits of between 2 days to 85 days? Or what should be the limits?

**Comment by ben-kaufman** [comment]
Well now it's 2 to 85. Should I close this issue?
