### ISSUE TITLE
Remove committee check in

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#284]
The committee check in just pauses vault deposits until the committee starts them for the first time. This seems practically the same as having a 0 address check, which is quite unnecessary. Also, note that we could just start vaults with depositPaused as true until governance starts them to give some time to do checks before starting the vault. Also, not that currently, the committee check in is only for the first time the committee is set, but if after check in the committee is replaced, there is no need committee check in which seems inconsistent.

**Comment by ben-kaufman** [comment]
We also maybe want to have the pause deposits controlled by the committee instead of owner. See https://github.com/hats-finance/hats-contracts/issues/280#issuecomment-1218165490

This will definitely make committee check in unnecessary.

**Comment by ben-kaufman** [comment]
@shayzluf @jellegerbrandy

**Comment by jellegerbrandy** [comment]
I am not sure if there is a legal argument here. Committee checkin is a kind of "acceptance of the responsibility" for the vault by the committee. You could say that as long as the committee has not checked in, hats gov is completely in control of the funds in the vault. i don't know, I am not a lawyer, but I always sort of assumed there was this kind of reason.

**Comment by lirona** [comment]
agree that vault should be initialized with deposits paused, and this way committee/gov can signal when vault is active and ready.

**Comment by ben-kaufman** [comment]
Ok so the suggestion would be to make the deposit paused controlled both by the committee and the governance, and to always start with the deposit as paused, and then remove the committee check in. Would that be good @jellegerbrandy @shayzluf ?

**Comment by shayzluf** [comment]
I would like to think more about committee incentive to pause the vault. Sounds good otherwise

**Comment by jellegerbrandy** [comment]
See also #291

**Comment by jellegerbrandy** [comment]
So not doing this bc of "governance can rugpull" argument
