### ISSUE TITLE
Should log claim be part of the individual vaults

### ISSUE THREAD

**Issue by ben-kaufman** [hats-finance/hats-contracts#285]
In the new architecture, should the logClaim function be part of the vault code, or rather be in the registry contract. I think the latter makes more sense but not sure.

**Comment by jellegerbrandy** [comment]
I see no argument either way. It's in the vault now, let's leave it in the vault :)

**Comment by lirona** [comment]
makes sense to me it's in the vault contract since it's connected to a specific vault, but i don't feel strongly about that either :)
