### ISSUE TITLE
setBountySplit separation

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#291]
Current, `setBountySplit` is set by governance. 
We want to te able to have that set by the creator of the vault when he calls `createVault`, and by the owner of the vault. However, we want hats governance to control the swapAndBurn and governanceHAT values 

What we can do:

1.  a new method `hatvaultregistry.setBountyFees(governanceHAT, hackerHatVested) onlyOwner` sets the percentage of the bounty that goes to governanceHat and hackerHatVested
1. `vault.setBountySplit(..) onlyOwner` (and `createVault`) can only set the distribution of the remaining values (hackerVested, hacker, committee)

The calculations will then be as follows:

- governanceHat + hatVested < 100%  
- hackerVested + hacker + committee = 100%

For example, if the total bounty = `bounty`, then:

- the amount reserved for governanceHat = `governanceHat/ 100%  * bounty`
- the amount reserver for hackerVested = `hackerVested/100% * (100%-(governanceHat + hatVested)) * bounty`

**Comment by lirona** [comment]
i think committee should not control the bounty split, since it can be people working for the project. are we assuming that vault creator is the project leadership?

**Comment by lirona** [comment]
guess just change them accordingly? (i mean change all other parts to have the same percentages of what's left)

**Comment by lirona** [comment]
we can have governance decide on the part of the bounty that get swapped to HATs (and how much of it goes to gov and how much to the hacker) and have the committee/project leadership decide on the devision of the rest between hacker, hacker vested and committee (so they give relative percentage out of what is left that is not swapped).
e.g gov decides on 10% swapped - 5% to hacker and 5% to gov, and committee/lead decide on division of 50% to hacker, 30% to hacker vested and 20% to committee (out of the non-swapped share) - so it means that 45% go to hacker, 27% go to hacker vested and 18% go to committee

**Comment by lirona** [comment]
we can have governance decide on the part of the bounty that get swapped to HATs (and how much of it goes to gov and how much to the hacker) and have the committee/project leadership decide on the devision of the rest between hacker, hacker vested and committee (so they give relative percentage out of what is left that is not swapped). this way both sides can change their values independently.
e.g gov decides on 10% swapped - 5% to hacker and 5% to gov, and committee/lead decide on division of 50% to hacker, 30% to hacker vested and 20% to committee (out of the non-swapped share) - so it means that 45% go to hacker, 27% go to hacker vested and 18% go to committee.

**Comment by ben-kaufman** [comment]
Sounds fine to me. Should we have any limits on the value that can be controlled by the hats governance or just whatever is set?

**Comment by lirona** [comment]
i think should have a limit and also the committee portion should be limited

**Comment by ben-kaufman** [comment]
We can only limit one side because the other side would take whatever is left for it.

**Comment by lirona** [comment]
what do you mean? i mean to limit only the governance part of the HATs side and only the committee part of the native token side (the hacker parts not limited)

**Comment by jellegerbrandy** [comment]
we have no limits  in v1, why do we need more limits now? We have time limits on the settability of this thing, if the users don't like the limits they can react.
