### ISSUE TITLE
hexen issue 2: loss of precision in tokenlock

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#360]
SEVERITY: Low
PATH: TokenLock.sol::L223
REMEDIATION: introduce a multiplier to maintain precision, or make sure the UI warns about the locked tokens if managedAmount is not a multiple of periods
STATUS:
DESCRIPTION:
This calculation loses the remainder of the division, and its result is multiplied by passedPeriods to construct the return value in availableAmount() at L272. For example, an amount of 109 over 10 periods claimed all at once at the end would return only 100 tokens, locking 9 into the contract forever. The maximum loss is `periods-1` tokens, if `managedAmount` is not a multiple of periods.

**Comment by jellegerbrandy** [comment]
@ben-kaufman says: "About hexens, #2 I think is not really important enough. We could add a multiplier, but there can always be a tiny loss of accuracy. It's just a few wei so not so important tbh. "

**Comment by jellegerbrandy** [comment]
I am not sure if this is a valid issue, the lines:

```
        // After contract ended all funds are available
        if (current > endTime) {
            return managedAmount;
        }


```
Add the remainder to the last claimed period, it seems to me

**Comment by lirona** [comment]
> I am not sure if this is a valid issue, the lines:
> 
> ```
>         // After contract ended all funds are available
>         if (current > endTime) {
>             return managedAmount;
>         }
> ```
> 
> Add the remainder to the last claimed period, it seems to me

yes looks like it solves it
