### ISSUE TITLE
Lack of Zero Address Validation

### ISSUE THREAD

**Issue by Shivang0** [hats-finance/hats-contracts#395]
The contract [HATTokenLock.sol](https://github.com/hats-finance/hats-contracts/blob/b9474779d02e7c18dd9cc74577ee692cd6d892f1/contracts/tokenlock/HATTokenLock.sol) is missing zero address checks in its [initializate() function](https://github.com/hats-finance/hats-contracts/blob/b9474779d02e7c18dd9cc74577ee692cd6d892f1/contracts/tokenlock/HATTokenLock.sol#L13). Every address should be validated and checked
that is different from zero. 

It should have a 
 ```
        require(!isInitialized, "Already initialized");
        require(_tokenLockOwner != address(0), "Owner cannot be zero");
        require(_beneficiary != address(0), "Beneficiary cannot be zero");
        require(_token != address(0), "Token cannot be zero");
        require(_managedAmount > 0, "Managed tokens cannot be zero");
        require(_startTime != 0, "Start time must be set");
        require(_startTime < _endTime, "Start time > end time");
        require(_periods >= MIN_PERIOD, "Periods cannot be below minimum");
        require(_revocable != Revocability.NotSet, "Must set a revocability option");
        require(_releaseStartTime < _endTime, "Release start time must be before end time");
        require(_vestingCliffTime < _endTime, "Cliff time must be before end time")
```

_Risk Level:_
Likelihood - 3 (Potential of a security incident in the long term.)
Impact - 2 (May cause temporary impact or loss.)
_Recommendation:_
It is recommended to validate that every address input is different from zero.

**Comment by lirona** [comment]
hi @Shivang0! thanks for your submission, we are aware of this and this is done on purpose in order to save gas. we have removed the address(0) checks from almost the entire code base and this checks are done in the frontend.
