### ISSUE TITLE
safeApprove() function is deprecated

### ISSUE THREAD

**Issue by masaun** [hats-finance/hats-contracts#396]
## Severity
- Medium

<br>

## Vulnerability description
- `safeApprove()` functuin has been deprecated by OpenZeppelin team: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2268
   - However, `safeApprove()` is used in the following lines in this repo:
      - https://github.com/hats-finance/hats-contracts/blob/develop/contracts/HATVault.sol#L320
      - https://github.com/hats-finance/hats-contracts/blob/develop/contracts/HATVault.sol#L329
      - https://github.com/hats-finance/hats-contracts/blob/develop/contracts/HATVaultsRegistry.sol#L415
      - https://github.com/hats-finance/hats-contracts/blob/develop/contracts/HATVaultsRegistry.sol#L427
 

<br>

## Mitigation steps
- Instead of using safeApprove() function, `safeIncreaseAllowance()` function and `safeDecreaseAllowance()` function should be used.
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#SafeERC20-safeIncreaseAllowance-contract-IERC20-address-uint256-
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#SafeERC20-safeDecreaseAllowance-contract-IERC20-address-uint256-

**Comment by lirona** [comment]
hi @masaun thanks for the submission. this is nice :)
have you submitted this issue through our dapp?

**Comment by masaun** [comment]
@lirona 
Sorry, I have submitted this issue via your dApp just now.

>but unfortunately not relevant for our use case:
Got it. I will try to find another issues.

**Comment by lirona** [comment]
great, good luck :)

**Comment by lirona** [comment]
can you please send the transaction hash to https://t.me/Hatsofir ? we don't see it

**Comment by masaun** [comment]
@lirona Sure, here is tx hash when I submitted: 
https://etherscan.io/tx/0x56c6dd9fdebb146cb416c3914b6ce05db3f300d124f9198469cd579202ce4061

**Comment by masaun** [comment]
>can you please send the transaction hash to https://t.me/Hatsofir ? we don't see it


@lirona Sure, I sent it just now. Could you check it?
