### ISSUE TITLE
 Improve MaxMint function

### ISSUE THREAD

**Issue by adeshkolte** [hats-finance/hats-contracts#397]
**Title:**
  **Description:** 
    function maxMint(address) public view virtual override returns (uint256) {
        return type(uint256).max;
    }

Share needs to subtract from totalsupply

For Reference : 
//@notice Gives the maximum amount of shares that can be minted by the receiver
    ///@return maxShares the maximum amount of shares available for mint
    function maxMint(address) public view returns (uint256 maxShares) {
        return type(uint256).max - _totalSupply;
    }

**Comment by lirona** [comment]
hi @adeshkolte thanks for the submission, but actually this is actually how the ERC4626 standard is supposed to be implemented:
https://eips.ethereum.org/EIPS/eip-4626
