### ISSUE TITLE
Missing Validation need to be Implemented  

### ISSUE THREAD

**Issue by adeshkolte** [hats-finance/hats-contracts#398]
Missing Validation need to be Implemented                                        
            
                
#Issue 1                    
• Severity: Minor
• Category: Procedural                                    
• Status :
• Source:    HATVaultsRegistry.sol    
Recommendation Should be "^0.8.16" or "^0.7.16" if there is something special about this particular version. Requiring a specific compiler version makes it harder to migrate to new compiler versions. Also relevant for the other files

#issue2
                                         
            
                
                    

• Severity Minor 
• Status
• Category Overflow/Underflow •
 Source :HATVaultsRegistry.sol
 Description: Phantom overflow is possible here.
Recommendation: Consider using the "mulDiv" function or some other approach resistant to phantom overflows in Calculation used in HATvaultRegistry.
                
            
        

                                         
            
                
                    
Issue#3
• Severity Minor • Status Fixed
• Category Bad datatype
 • Source :l HATVaultsRegistry.sol
Recommendation :The type of the token arguments should be ’IERC20".
        InsteadOf address you can use “IERC20”        
            
        
                          F
unction swapAndSend(
       address _asset,
       address[] calldata _beneficiaries,
       uint256 _amountOutMinimum,
       address _routingContract,
       bytes calldata _routingPayload
   ) external onlyOwner
            
        
#Issue4
Improve the following code by adding check
Validation Missing in CreateVault Function 

Recommendation: Add Require Check
function createVault(
       IERC20 _asset,
       address _owner,
       address _committee,
       IRewardController _rewardController,
       uint256 _maxBounty,
       HATVault.BountySplit memory _bountySplit,
       string memory _descriptionHash,
       uint256 _bountyVestingDuration,
       uint256 _bountyVestingPeriods,
       bool _isPaused
   )
   external
   returns(address vault)
   {
       require(
           hatVaultImplementation != address(0),
           "vault implement not set yet"
       );
       vault = Clones.clone(hatVaultImplementation);
 
       HATVault(vault).initialize(
           IHATVault.VaultInitParams({
               rewardController: _rewardController,
               vestingDuration: _bountyVestingDuration,
               vestingPeriods: _bountyVestingPeriods,
               maxBounty: _maxBounty,
               bountySplit: _bountySplit,
               asset: _asset,
               owner: _owner,
               committee: _committee,
               isPaused: _isPaused,
               descriptionHash: _descriptionHash
           })
       );
 
       hatVaults.push(vault);
 
       emit VaultCreated(
           vault,
           address(_asset),
           _committee,
           _rewardController,
           _maxBounty,
           _bountySplit,
           _descriptionHash,
           _bountyVestingDuration,
           _bountyVestingPeriods,
           _isPaused
       );
   }

**Comment by lirona** [comment]
hi @adeshkolte! thanks for your submission :) 
as for your issues:
1. Actually it should be better to use a specific version in order to avoid unexpected behavior.
for example see this recommendation from hardhat:
https://hardhat.org/hardhat-runner/docs/guides/compile-contracts
2. this shouldn't be a problem in solidity 0.8, can you explain more or reference this problem?
3. why would that be better? could you also explain or reference please?
4. we removed all address(0) checks from the code base to save gas. where it's necessary it is done on the frontend

**Comment by jellegerbrandy** [comment]
abt 2: so this is abt "phantom overflow", which is when you get an overflow error which could be avoided. The example is if you want to calculate say 7% of something, we do `someValue * 7 /100`, then if `someValue` is very big you may get an overflow error when calculating `someValue * 7`.

What `mulDiv` library does is help out and in these cases calculate the result as `(someValue / 100) * 7`, which is nice. It is not something that I think would happen in real life with the numbers we are using, but if @adeshkolte has a specific line where this would be a problem I'd be very happy to know :)
