### ISSUE TITLE
Able to claim reward more than once and a broken test

### ISSUE THREAD

**Issue by BoxedFruits** [hats-finance/hats-contracts#403]
# Severity
High
#402
# Description
Whenever a user is claiming a reward, they should try to call `claimReward` in `RewardController.sol`.
https://github.com/hats-finance/hats-contracts/blob/15b37a68f97f8f737a8808a9ff55d60bc2376d7e/contracts/RewardController.sol#L159-L169

The function should set the `unclaimedReward` mapping to 0 for the user after [transferring the reward](https://github.com/hats-finance/hats-contracts/blob/develop/contracts/RewardController.sol#L164). However `_commitUserBalance` changes `unclaimedReward` at the beginning of this function back to its original [state](https://github.com/hats-finance/hats-contracts/blob/develop/contracts/RewardController.sol#L137-L140). Because a user can set the state and act like they  never claimed a reward, **they can call the `claimReward` function any number of times and drain the RewardsController of all of its rewardTokens**

## Broken Test
 There is a test written for this scenario, however since it is being sent in the same block, it stops here https://github.com/hats-finance/hats-contracts/blob/develop/contracts/RewardController.sol#L75-L77. 
 
 The test in question: https://github.com/hats-finance/hats-contracts/blob/15b37a68f97f8f737a8808a9ff55d60bc2376d7e/test/hatvaults.js#L2135-L2173
 
Which uses this mock that sends the `claimReward` call twice in the same block, which lead this bug to fly under the radar : https://github.com/hats-finance/hats-contracts/blob/15b37a68f97f8f737a8808a9ff55d60bc2376d7e/contracts/mocks/PoolsManagerMock.sol#L43-L46

**Comment by lirona** [comment]
hi @BoxedFruits, thanks for your submission!
actually what happens if it's called twice not in the same block is that more rewards become available since the first claim (they get accumulated with every block that passes), so the second claimReward would transfer a new reward that is rightfully theirs :) so no bug here..
