### ISSUE TITLE
Access Control Issue

### ISSUE THREAD

**Issue by Shivang0** [hats-finance/hats-contracts#409]
[CreateTokenLock](https://github.com/hats-finance/hats-contracts/blob/develop/contracts/tokenlock/TokenLockFactory.sol#L66) Function has an access control issue. Access control plays an important role in segregation of privileges in smart contracts and other applications. If this is misconfigured or not properly validated on sensitive functions, it may lead to loss of funds, tokens and in some cases compromise of the smart contract.

```
    function createTokenLock(
        address _token,
        address _owner,
        address _beneficiary,
        uint256 _managedAmount,
        uint256 _startTime,
        uint256 _endTime,
        uint256 _periods,
        uint256 _releaseStartTime,
        uint256 _vestingCliffTime,
        ITokenLock.Revocability _revocable,
        bool _canDelegate
    ) external override returns(address contractAddress) {
        // Create contract using a minimal proxy and call initializer
        bytes memory initializer = abi.encodeWithSignature(
            "initialize(address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint8,bool)",
            _owner,
            _beneficiary,
            _token,
            _managedAmount,
            _startTime,
            _endTime,
            _periods,
            _releaseStartTime,
            _vestingCliffTime,
            _revocable,
            _canDelegate
        );
```

The contract TokenLockFactory is importing an access control library @openzeppelin/contracts/access/Ownable.sol but the function createTokenLock is missing the modifier onlyowner or OnlyBeneficiary or similar role.

It is recommended to go through the contract and observe the functions that are lacking an access control modifier. If they contain sensitive administrative actions, it is advised to add a suitable modifier to the same

**Comment by lirona** [comment]
hi @Shivang0, thanks for your submission! have you submitted this through our dapp as well? if so can you please give the transaction hash?

**Comment by Shivang0** [comment]
hi @lirona , i wasn't able to submit it via dApp as the contest ended before I was able to send the report.

**Comment by lirona** [comment]
got it. anyway there's no reason as far as we can see to have an access modifier on this function. can you think of why it is needed?

**Comment by Shivang0** [comment]
The reason is because OnlyCommittee or onlyOwner or similar high level access account should have Access to createToken Lock not every user.

**Comment by jellegerbrandy** [comment]
my friend you are just repeating that we should have access control, not giving us a reason :)
