### ISSUE TITLE
allow for arbitrator to submit claim [to be discussed]

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#496]
context is here: https://docs.google.com/document/d/10q0z1g9lNo9naKqwTE7uEGpC5HuneZ9tklhpfVs9_AY/edit#heading=h.16212i9jmsiu

this would allow hackers to bypass the committee altogether and ask kleros to submit a claim directly (this claim can then be disputed later)

**Comment by jellegerbrandy** [comment]
one thing about this: if the arbitratror can submit and then judge claims, it is in control of the entire process. It makes sense at this point to abstract the entire submit-claim-and-then-decide-what-to-do out of the hatvaults contract, and into a separate "arbitrator" contract, that in turn can implement either the committee-hatsgov flow, or the committee-kleros flow, or the committee-auditarbitrator-hatsgov flow, etc

i.e. what i am saying that instead of adding little pieces of functionality incrementally, perhaps this calls for a more principles refactor. 

this will also diminish the hatvaults size, which has been a problem

**Comment by ben-kaufman** [comment]
Yes I think it would make sense to move this logic out if we want to allow more flexibility in how it's managed, but it's a big change we'd need to think about how to do this

**Comment by ben-kaufman** [comment]
Done in #503
