### ISSUE TITLE
Migration from v1 to v2

### ISSUE THREAD

**Issue by jellegerbrandy** [hats-finance/hats-contracts#93]
As the contract is not upgradeable, we must find a way to migrate the funds and users. Ideally, this migration would require no action on the part of the user. 

## Migration process
The idea is for each pool we:

(A) pause the original pool 
(B) send the funds over to the new contract
(C) take a snapshot of the distribution of shares and create a pool on the new contact with the same settings and shares distribution as the old contract

1. Governance pauses deposits to the original pool by calling `setPool` with `_depositPause = false`.
2. (governance calls `setRewardsLevelsDelay(pid, 2 days)` to set the daly to  the minimum of 2 days , only if the current value is higher)
3. Governance calls `setPendingRewardsLevels(pid, [10000-1])` to create single rewards level that will pay out 99.99% of the pool
5.  Two days later, governance calls `setRewardsLevels()` 
5.   Governance calls `setRewardsSplit(pid, rewardsplit)` where `rewardsplit` sets all values to `0` except for `hackerReward` which should be set to `10000`
6. **Committee** creates a claim by calling `pendingApprovalClaim(pid, newVaultsAddress, 0)` (where 0 denotes the 99.99% severity level). 
7. At this point both deposits and withdrawals from the pool are pause. The migraiton script takes a snapshot of all shares (i.e. for each account it's `balance` and `rewardDebt`), to be used later
8. Governance calls `approveClaim(pid)` which will send 99.99% of the funds to the new contract 😅 
9. Governance creates a new pool on the new contract by calling `addPool(allocPoint, lpToken, rewardsLevels, rewardsSplit, descriptionHash, rewardVestingParams, rewardPerShare, balance, depositPause)` with the same  settings as the original pool
10. Governance transfers the shares distribution of the previous pool to the new one by calling a **new function** called `setShares(uint256 _pid, address[] accounts, uint256[] shares, uint256[] rewardDebts)`, reading the values from the original pool. If there are a lot of shares, this function perhaps needs to be called several times to stay within the gas limit  --> See specs of this new function below
11.  Governance unpauses the vault by calling `setVault(pid, ...)`
12. The **committee** calls `committeeCheckIn` on the new contract

### New arguments in `addPool`

We add new parameters to the `addPool` function which will now look like this:
```
    function addPool(uint256 _allocPoint,
                    address _lpToken,
                    address _committee,
                    uint256[] memory _rewardsLevels,
                    RewardsSplit memory _rewardsSplit,
                    string memory _descriptionHash,
                    uint256[2] memory _rewardVestingParams,
           uint256 rewardPerShare,
           uint256 balance,
           bool isPaused
)
```

### New function `setShares`

```
function setShares(pid, address[] accounts, uint256[] shares, uint256[] rewardDebts) onlyGovernance {
       require(poolInitialized[pid] == false)
      ... loop over the accounts and set balance and rewardDebt as per the arguments...
}
 ```

Sets the shares of the users. 

### maybe also add an "initializing" state to limit the application of setShares? (discuss)

`setShares` gives even more power to Governance, and also allows to really mess with the pool state (it can easily steal the shares of honest depositors) so it makes sense to limit that call only to the "initialisation" state (i.e. before any other deposits or withdraws are made)

 `initialized` will be a new state of the pools. During initilizaiton (i..e when `initialized` is false) we can call `setShares`. 
 Once a pool is initialized, it cannot raeturn to an uninitialized state. 

There will be a new function 

```
function isInitialized(pid) onlyGovernance {
       require(poolInitialized[pid] = false)
       poolInitialized[pid] = true;
} 
```

The `addPool` function will have a new argument, `isInitialized`, which by default is true. 

`setShares` will contain a `require(poolInitialized[pid] = false)`

In this migration scenario, we set `isInitialized` to `false` so we can call `setShares`

All this is pretty clumsy, so if someone has a better idea?

**Comment by jellegerbrandy** [comment]
To make sure that when adding a second pool which uses the same token as the first, the new pool does not "steal" money from the first pool, we should require that the total of the `pool.balance` for each pool does not exceed the actual token balance of the contract.

**Comment by ben-kaufman** [comment]
Not sure what's this setVault thing in step 11?

**Comment by ben-kaufman** [comment]
Closing as we decided not to go with this migration plan
